import { readFileSync, writeFileSync } from "node:fs";
import { booleanConfiguration, integerConfiguration, parseRuntimeConfiguration } from "../src/lib/runtime-config";
import { settingsContract, validateSettings } from "../src/lib/settings-contract";

const referencePath = new URL("../docs/configuration-contract.md", import.meta.url);
const environmentExample = {
  PUBLIC_URL: "https://terraform.example.com",
  PORT: "3000",
  SYSTEM_API_PORT: "8443",
  TERRENCE_RUN_SANDBOX: "true",
  TERRENCE_RUN_NET_POLICY: "deny",
  TERRENCE_RUN_CONCURRENCY: "5",
};
const settingsExample = { "plan-timeout": 3600, "apply-timeout": 3600, "api-rate-limit": 60 };

/** Generate the reference from the same rules used by the server. */
export function configurationReference(): string {
  parseRuntimeConfiguration(environmentExample, true);
  validateSettings("general", settingsExample, true);
  const rows = Object.entries(integerConfiguration).map(([name, rule]): string =>
    `| ${name} | ${String(rule.default)} | Integer ${String(rule.min)}–${String(rule.max)} |`);
  rows.push(...Object.entries(booleanConfiguration).map(([name, value]): string =>
    `| ${name} | ${String(value)} | true, false, 1, or 0 |`));
  const persistedRows = Object.entries(settingsContract).flatMap(([group, rules]): string[] =>
    Object.entries(rules).map(([key, rule]): string => {
      const range = rule.kind === "integer" ? ` ${String(rule.min)}–${String(rule.max)}` : "";
      const choices = rule.choices === undefined ? "" : ` (${rule.choices.join(", ")})`;
      return `| ${group}.${key} | ${rule.kind}${range}${choices}${rule.nullable === true ? " or null" : ""} | ${rule.sensitive === true ? "redacted" : "visible"} |`;
    }));
  return `# Configuration contract

Generated by \`bun backend/scripts/configuration-reference.ts --write\`.
Verify with \`bun backend/scripts/configuration-reference.ts --check\`.
The generator validates the examples using the server's configuration rules.

## Deployment settings

The settings below are parsed before database initialization. Only absent values
inherit defaults. Invalid explicit values fail startup. Environment changes require
a process restart. Millisecond timeouts are bounded to avoid timer overflow.
Unknown names in application-owned namespaces such as TERRENCE_, SYSTEM_API_, and
RATE_LIMIT_ fail startup. Unrelated process variables remain available.

| Name | Default | Accepted values |
| --- | --- | --- |
${rows.sort().join("\n")}

PUBLIC_URL accepts an HTTP(S) URL without credentials, query, or fragment.
CORS_ORIGIN accepts comma-separated HTTP(S) origins without paths; an empty value
means no explicit origin list. TERRENCE_RUN_SANDBOX accepts true/false and the
aliases 1/0, yes/no, on/off, and none (disabled). TERRENCE_RUN_NET_POLICY accepts
allow or deny; deny requires the sandbox. TERRENCE_EXECUTOR_BACKEND accepts
landlock, container, kubernetes, agent, or microvm and defaults to landlock.
TERRENCE_SANDBOX_MIN_ABI is optional; when set it must be an integer from 1 to 255.
Declaring an executor does not install it. PORT and SYSTEM_API_PORT must differ.

STORAGE_DIR defaults to backend/storage and must be a non-empty filesystem path.
SYSTEM_API_HOST defaults to 127.0.0.1. SYSTEM_API_TLS_CERT and SYSTEM_API_TLS_KEY
must be configured together as non-empty file paths; startup also checks that
the files exist and contain data. Remote host bindings require this TLS pair.
The existing container wildcard bindings 0.0.0.0 and :: remain supported.
Paths are redacted in the effective-configuration report.
TERRENCE_SANDBOX_EXTRA_RW_PATHS accepts at most 32 colon-separated absolute paths
and requires TERRENCE_SANDBOX_EXTRA_RW_ALLOWED. Paths that contain storage, lie
inside it, or equal it also require TERRENCE_SANDBOX_EXTRA_RW_ALLOW_STORAGE.

TERRENCE_TRUSTED_PROXY_CIDRS and TERRENCE_OUTBOUND_ALLOW_CIDRS accept comma-separated
IPv4 addresses or CIDRs. TERRENCE_OUTBOUND_ALLOW_HOSTS accepts comma-separated
hostnames. Each list accepts at most 256 entries and defaults to empty. Invalid
entries are rejected; IPv6 CIDRs are not supported by the current enforcement code.

GITHUB_API_URL defaults to https://api.github.com. GITHUB_APP_API_URL overrides
that base for GitHub App requests. GITHUB_APP_HTTP_URL is an optional web-base
override. These inputs accept HTTP(S) URLs without credentials, queries, or
fragments; empty explicit values are invalid. Their report values are redacted.

TERRENCE_NODE_STATUS accepts active (default), draining, or maintenance.
TERRENCE_AGENT_UPDATE_VERSION, TERRENCE_AGENT_UPDATE_URL, and
TERRENCE_AGENT_UPDATE_SHA256 must be configured together. The update URL must be
HTTP(S) without embedded credentials or a fragment; query parameters are allowed
for signed download URLs. SHA256 must contain exactly 64 hexadecimal characters.
The version accepts at most 128 letters, digits, dots, underscores, plus or minus
signs. An absent update triple disables update advertising; an invalid one fails
startup. Update URLs are redacted from the effective report.

SIGNED_URL_SECRET requires at least 32 characters; TERRENCE_TOKEN_HASH_SECRET
requires at least 32 UTF-8 bytes. Both retain their existing trimming behavior.
ENCRYPTION_PASSWORD is preserved verbatim and must be non-empty when supplied.
These secrets are limited to 65,536 characters (SIGNED_URL_SECRET) or UTF-8 bytes
(the other two), cannot contain NUL, require restart, and are always redacted.
Absent signing/hash secrets retain the existing persistent generated-key behavior;
an absent encryption password retains the installation-key behavior.

LOG_LEVEL defaults to info and accepts error, warn, info, or debug.
TERRENCE_SYSLOG_LEVEL inherits LOG_LEVEL. TERRENCE_SYSLOG_FORMAT accepts
rfc5424 (default) or json. TERRENCE_SYSLOG_TARGETS accepts up to 16 comma- or
newline-separated udp://host:port or tcp://host:port destinations. The legacy
TERRENCE_SYSLOG_TARGET alias is accepted; conflicting aliases are rejected.
TERRENCE_SYSLOG_HOSTNAME and TERRENCE_SYSLOG_APP accept printable ASCII without
spaces, at most 255 and 48 characters respectively. The app defaults to terrence;
the hostname is auto-detected when absent. These settings require restart.

Validated environment example:

\`\`\`json
${JSON.stringify(environmentExample, null, 2)}
\`\`\`

## Persisted settings covered by the contract

Admin updates are validated before saving. Invalid submitted values return 422.
Invalid stored configuration prevents startup and returns 503 when encountered
during a settings read. Corrections are validated as a complete merged group.
Unknown fields within these groups are rejected.

| Setting | Accepted type or range | Report value |
| --- | --- | --- |
${persistedRows.sort().join("\n")}

Enabled OIDC requires issuer and client-id. A client secret is required unless
using S256 without a symmetric signing algorithm. Enabled LDAP requires host and
base-dn; a service-account bind DN requires a bind password. OIDC issuer URLs must
use HTTPS, except HTTP on localhost or a loopback address, and cannot contain
credentials, queries, or fragments.

Validated general-settings attributes:

\`\`\`json
${JSON.stringify(settingsExample, null, 2)}
\`\`\`

## Effective values

The admin-only GET /api/v2/admin/system-info response includes
deployment-configuration and persisted-configuration. Entries identify the value's
origin and whether a restart is required. Sensitive persisted values are redacted.
Persisted changes take effect on the next settings read; cache lifetime is at most
one second. Already running operations retain values captured when they started.
`;
}

if (import.meta.main) {
  const content = configurationReference();
  if (process.argv.includes("--write")) writeFileSync(referencePath, content);
  else if (readFileSync(referencePath, "utf8") !== content) {
    throw new Error("Configuration reference is stale; regenerate it with --write");
  }
}
