#!/usr/bin/env bun
/**
 * Generate backend/src/db/schema.ts — the dialect selector module.
 *
 * The canonical schema lives in db/schema-sqlite.ts (sqlite-core). This
 * generated module re-exports every table under the sqlite TYPES (so all
 * existing call sites keep their types) while resolving the runtime VALUE
 * to the active dialect's table object:
 *
 *   - sqlite backend  -> the sqlite table (unchanged behavior)
 *   - postgres backend -> the pg table built by pg-convert.buildPgSchema()
 *
 * Regenerate with: bun run scripts/generate-schema-selector.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import * as schema from "../src/db/schema-sqlite";

const OUT = join(import.meta.dir, "../src/db/schema.ts");
const NAME = Symbol.for("drizzle:Name");

const tableNames: string[] = [];
for (const [key, value] of Object.entries(schema)) {
  if (value !== null && typeof value === "object" && (value as Record<PropertyKey, unknown>)[NAME] !== undefined) {
    tableNames.push(key);
  }
}

const lines: string[] = [];
lines.push("/* eslint-disable */");
lines.push("// AUTO-GENERATED by scripts/generate-schema-selector.ts — DO NOT EDIT.");
lines.push("// Dialect selector: sqlite-core tables are canonical (see schema-sqlite.ts);");
lines.push("// when the postgres backend is active, the pg tables built by pg-convert.ts");
lines.push("// are re-exported under the same names. Types always come from the sqlite");
lines.push("// definitions, so call sites are dialect-agnostic by construction.");
lines.push("import * as sqliteSchema from \"./schema-sqlite\";");
lines.push("import { buildPgSchema } from \"./pg-convert\";");
lines.push("import { resolveDatabaseConfig } from \"../lib/boot-config\";");
lines.push("import { join, resolve } from \"node:path\";");
lines.push("");
lines.push("const storageDir = resolve(process.env.STORAGE_DIR ?? join(import.meta.dir, \"../../storage\"));");
lines.push("const activeDriver = resolveDatabaseConfig(process.env, storageDir).driver;");
lines.push("// Built lazily: constructing the pg mirror walks every sqlite table object,");
lines.push("// which is wasted work on the sqlite path and can throw on exotic schema");
lines.push("// constructs the mirror does not understand.");
lines.push("const pgTables = activeDriver === \"postgres\" ? buildPgSchema(sqliteSchema) : null;");
lines.push("");
lines.push("const dbNameOf = (table: object): string =>");
lines.push("  String((table as Record<PropertyKey, unknown>)[Symbol.for(\"drizzle:Name\")]);");
lines.push("");
for (const name of tableNames) {
  lines.push(`export const ${name}: typeof sqliteSchema.${name} = pgTables === null`);
  lines.push(`  ? sqliteSchema.${name}`);
  lines.push(`  : (pgTables[dbNameOf(sqliteSchema.${name})] as unknown as typeof sqliteSchema.${name});`);
  lines.push("");
}

mkdirSync(join(import.meta.dir, "../src/db"), { recursive: true });
writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT} (${tableNames.length} tables)`);
