import { createHash } from "node:crypto";
import { and, desc, eq } from "drizzle-orm";
import { db } from "../db";
import { runExplanations } from "../db/schema";
import { readPlanJsonArtifact } from "./plan-json";
import { readRunLogs } from "./run-logs";
import { log } from "./log";

/**
 * AI run explainer (kanban 21.2): plain-language explanations of a stored
 * plan JSON or a failed apply log, generated by a user-configured
 * OpenAI-compatible endpoint. Results are cached per (run, kind) so re-opening
 * the dialog never re-burns tokens; a regenerate action forces a fresh call.
 * All state lives in the `run_explanations` table; the upstream call itself is
 * never part of the trusted apply decision.
 */
export type ExplainKind = "plan" | "apply";

export const EXPLAIN_KINDS: readonly ExplainKind[] = ["plan", "apply"];

export const EXPLAIN_MAX_PROMPT_CHARS = 100_000;
export const EXPLAIN_APPLY_LOG_TAIL_CHARS = 40_000;
export const EXPLAIN_MAX_TOKENS = 500;
export const EXPLAIN_TIMEOUT_MS = 60_000;

export type ExplainSource = Readonly<{
  prompt: string;
  inputHash: string;
}>;

export type StoredExplanation = Readonly<{
  id: string;
  runId: string;
  kind: ExplainKind;
  model: string;
  content: string;
  thinking: string | null;
  inputHash: string;
  createdAt: number;
}>;

/**
 * Build the prompt (and its content hash) for a run kind. Returns undefined
 * when the run has no artifact to explain (callers map that to 409).
 * The input hash is the cheap staleness detector: a new plan or a changed
 * apply log yields a different hash, so the cache serves fresh content only.
 */
export async function buildExplainSource(runId: string, kind: ExplainKind): Promise<ExplainSource | undefined> {
  if (kind === "plan") {
    const planJson = await readPlanJsonArtifact(runId);
    if (planJson === undefined) return undefined;
    const serialized = JSON.stringify(planJson);
    const truncated = serialized.length > EXPLAIN_MAX_PROMPT_CHARS
      ? `${serialized.slice(0, EXPLAIN_MAX_PROMPT_CHARS)}\n... (truncated)`
      : serialized;
    const prompt = `Explain the following Terraform plan in plain language for a reviewer. Summarize what will be added, changed, and destroyed, flag anything risky, and keep it under 250 words.\n\n${truncated}`;
    return { prompt, inputHash: hashInput(prompt) };
  }
  const logEntries = await readRunLogs(runId, "apply");
  if (logEntries.length === 0) return undefined;
  const fullLog = logEntries.map((entry) => entry.outputText).join("\n");
  const tail = fullLog.length > EXPLAIN_APPLY_LOG_TAIL_CHARS
    ? `... (earlier output omitted)\n${fullLog.slice(-EXPLAIN_APPLY_LOG_TAIL_CHARS)}`
    : fullLog;
  const prompt = `The following Terraform apply failed. Explain in plain language what went wrong, quote the key error, and suggest the most likely fix. Keep it under 250 words.\n\n${tail}`;
  return { prompt, inputHash: hashInput(prompt) };
}

function hashInput(prompt: string): string {
  return createHash("sha256").update(prompt).digest("hex");
}

/**
 * Latest cached explanation for a (run, kind). A row is a cache hit only when
 * both the model and the artifact hash still match, so a reconfigured model or
 * a re-planned run transparently regenerates instead of serving stale text.
 */
export async function findExplanation(runId: string, kind: ExplainKind, model: string, inputHash: string): Promise<StoredExplanation | undefined> {
  const rows = await db.query.runExplanations.findMany({
    where: and(eq(runExplanations.runId, runId), eq(runExplanations.kind, kind)),
    orderBy: [desc(runExplanations.createdAt)],
    limit: 1,
  });
  const row = rows[0];
  if (row === undefined) return undefined;
  if (row.model !== model || row.inputHash !== inputHash) return undefined;
  return {
    id: row.id,
    runId: row.runId,
    kind: row.kind as ExplainKind,
    model: row.model,
    content: row.content,
    thinking: row.thinking,
    inputHash: row.inputHash,
    createdAt: row.createdAt,
  };
}

/**
 * Persist a fresh explanation for (run, kind), replacing any earlier one.
 * One row per (run, kind): the latest generation is the cache.
 */
export async function saveExplanation(
  runId: string,
  kind: ExplainKind,
  model: string,
  content: string,
  thinking: string | null,
  inputHash: string,
): Promise<void> {
  await db.delete(runExplanations).where(and(eq(runExplanations.runId, runId), eq(runExplanations.kind, kind)));
  await db.insert(runExplanations).values({
    id: `rex-${crypto.randomUUID()}`,
    runId,
    kind,
    model,
    content,
    thinking: thinking !== null && thinking !== "" ? thinking : null,
    inputHash,
  });
}

export type CompletionParts = Readonly<{ content: string; thinking: string }>;

/**
 * Split inline thinking tags out of accumulated text. Covers providers that
 * stream reasoning inside content as <thinking>...</thinking> (Qwen-style)
 * instead of a separate reasoning_content channel. Only the outermost
 * occurrence is honored per tag name; content before the first opening tag
 * stays content.
 */
export function splitInlineThinking(raw: string): CompletionParts {
  const opening = /<(thinking|reasoning)>/i.exec(raw);
  if (opening === null) return { content: raw, thinking: "" };
  const tagName = opening[1]?.toLowerCase() ?? "thinking";
  const closing = new RegExp(`</${tagName}>`, "i").exec(raw.slice(opening.index + opening[0].length));
  if (closing === null) return { content: raw, thinking: "" };
  const content = `${raw.slice(0, opening.index)}${raw.slice(opening.index + opening[0].length + closing.index + closing[0].length)}`;
  const thinking = raw.slice(opening.index + opening[0].length, opening.index + opening[0].length + closing.index);
  return { content, thinking };
}

/**
 * Common upstream request builder. `stream: true` asks the provider for an
 * SSE response; providers that ignore the flag and return plain JSON are
 * handled by the caller via content-type sniffing.
 */
export function upstreamRequest(settings: Readonly<Record<string, unknown>>, prompt: string, stream: boolean): Request {
  const endpointUrl = settings["endpoint-url"] as string;
  const model = settings.model as string;
  const apiKey = typeof settings["api-key"] === "string" && settings["api-key"] !== "" ? settings["api-key"] : undefined;
  return new Request(endpointUrl, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      ...(apiKey !== undefined ? { authorization: `Bearer ${apiKey}` } : {}),
    },
    body: JSON.stringify({ model, messages: [{ role: "user", content: prompt }], max_tokens: EXPLAIN_MAX_TOKENS, stream }),
  });
}

/** Non-streaming completion parse: content + optional reasoning/thinking. */
export function parseCompletionBody(parsed: unknown): CompletionParts {
  const choices = (parsed as Readonly<{ choices?: ReadonlyArray<Readonly<{ message?: Readonly<Record<string, unknown>> }>> }>)?.choices;
  const message = choices?.[0]?.message;
  const contentValue = message?.content;
  let content = typeof contentValue === "string" ? contentValue : "";
  let thinking = "";
  const reasoningContent = message?.["reasoning_content"];
  const reasoning = message?.reasoning;
  if (typeof reasoningContent === "string" && reasoningContent !== "") {
    thinking = reasoningContent;
  } else if (typeof reasoning === "string" && reasoning !== "") {
    thinking = reasoning;
  } else if (typeof reasoning === "object" && reasoning !== null) {
    const raw = JSON.stringify(reasoning);
    if (raw !== undefined && raw !== "") thinking = raw;
  }
  if (thinking === "") {
    const split = splitInlineThinking(content);
    content = split.content;
    thinking = split.thinking;
  }
  return { content, thinking };
}

/**
 * Throttle a raw upstream SSE stream into (reasoning, content) channels,
 * covering the two mainstream OpenAI-compatible conventions:
 *   - delta.reasoning_content (DeepSeek and its clones)
 *   - delta.reasoning (OpenAI-style reasoning models)
 * inline <thinking> tags inside delta.content pass through unmodified and are
 * split at finalize time (see splitInlineThinking).
 */
export async function forEachUpstreamDelta(
  upstream: Readonly<Response>,
  onDelta: (channel: "thinking" | "content", text: string) => void | Promise<void>,
): Promise<void> {
  if (upstream.body === null) return;
  const reader = upstream.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed.startsWith("data:")) continue;
      const payload = trimmed.slice(5).trim();
      if (payload === "" || payload === "[DONE]") continue;
      let chunk: unknown;
      try {
        chunk = JSON.parse(payload);
      } catch {
        continue;
      }
      const delta = (chunk as Readonly<{ choices?: ReadonlyArray<Readonly<{ delta?: Readonly<Record<string, unknown>> }>> }>)?.choices?.[0]?.delta;
      if (delta === undefined) continue;
      const content = delta.content;
      if (typeof content === "string" && content !== "") await onDelta("content", content);
      const reasoningContent = delta["reasoning_content"];
      const reasoning = delta.reasoning;
      const thinkingPart = typeof reasoningContent === "string" && reasoningContent !== ""
        ? reasoningContent
        : typeof reasoning === "string" && reasoning !== ""
          ? reasoning
          : "";
      if (thinkingPart !== "") await onDelta("thinking", thinkingPart);
    }
  }
}

/** Shared upstream fetch with timeout; failures are reported via thrown Error. */
export async function fetchUpstream(settings: Readonly<Record<string, unknown>>, prompt: string, stream: boolean, signal?: Readonly<AbortSignal>): Promise<Response> {
  const controller = new AbortController();
  const timeout = setTimeout((): void => controller.abort(new Error("request timed out")), EXPLAIN_TIMEOUT_MS);
  const onExternalAbort = (): void => controller.abort();
  signal?.addEventListener("abort", onExternalAbort, { once: true });
  try {
    return await fetch(upstreamRequest(settings, prompt, stream), { signal: controller.signal });
  } catch (error: unknown) {
    throw new Error(`Plan explainer endpoint unreachable: ${error instanceof Error ? error.message : String(error)}`, { cause: error });
  } finally {
    clearTimeout(timeout);
    signal?.removeEventListener("abort", onExternalAbort);
  }
}

/** Standard JSON error envelope used by the explain routes. */
export function explainError(status: number, title: string, detail: string): Readonly<{ status: number; body: unknown }> {
  return { status, body: { errors: [{ status: String(status), title, detail }] } };
}

export { log };