import { and, desc, eq } from "drizzle-orm";
import { db } from "../db";
import { runExplanations } from "../db/schema";
import { readPlanJsonArtifact } from "./plan-json";
import { readRunLogs } from "./run-logs";
import { log } from "./log";

/**
 * AI run explainer (kanban 21.2): plain-language explanations of a stored
 * plan JSON or a failed apply log, generated by a user-configured
 * OpenAI-compatible endpoint. Results are cached per (run, kind) so re-opening
 * the dialog never re-burns tokens; a regenerate action forces a fresh call.
 * Only the final answer is cached; transient provider reasoning is never persisted.
 * Cache identity is the run and explanation slot, never the current model or
 * reasoning configuration.
 * All state lives in the `run_explanations` table; the upstream call itself is
 * never part of the trusted apply decision.
 */
export type ExplainKind = "plan" | "apply";

export const REASONING_EFFORTS = ["none", "minimal", "low", "medium", "high", "xhigh", "max"] as const;
export type ReasoningEffort = typeof REASONING_EFFORTS[number];

export const EXPLAIN_KINDS: readonly ExplainKind[] = ["plan", "apply"];

export const EXPLAIN_MAX_PROMPT_CHARS = 100_000;
export const EXPLAIN_APPLY_LOG_TAIL_CHARS = 40_000;
export const EXPLAIN_TIMEOUT_MS = 60_000;

export type ExplainSource = Readonly<{
  prompt: string;
}>;

export function configuredReasoningEffort(value: unknown): ReasoningEffort | null {
  return typeof value === "string" && (REASONING_EFFORTS as readonly string[]).includes(value) ? value as ReasoningEffort : null;
}

export type StoredExplanation = Readonly<{
  id: string;
  runId: string;
  kind: ExplainKind;
  model: string;
  content: string;
  createdAt: number;
}>;

/**
 * Build the prompt for a run kind. Returns undefined
 * when the run has no artifact to explain (callers map that to 409).
 */
export async function buildExplainSource(runId: string, kind: ExplainKind): Promise<ExplainSource | undefined> {
  if (kind === "plan") {
    const planJson = await readPlanJsonArtifact(runId);
    if (planJson === undefined) return undefined;
    const serialized = JSON.stringify(planJson);
    const truncated = serialized.length > EXPLAIN_MAX_PROMPT_CHARS
      ? `${serialized.slice(0, EXPLAIN_MAX_PROMPT_CHARS)}\n... (truncated)`
      : serialized;
    const prompt = `Explain the following Terraform plan in plain language for a reviewer. Provide a brief overview of what will be added, changed, or destroyed, and flag anything risky. Use concise bullets where helpful; do not reproduce the full plan or your internal reasoning.\n\n${truncated}`;
    return { prompt };
  }
  const logEntries = await readRunLogs(runId, "apply");
  if (logEntries.length === 0) return undefined;
  const fullLog = logEntries.map((entry) => entry.outputText).join("\n");
  const tail = fullLog.length > EXPLAIN_APPLY_LOG_TAIL_CHARS
    ? `... (earlier output omitted)\n${fullLog.slice(-EXPLAIN_APPLY_LOG_TAIL_CHARS)}`
    : fullLog;
  const prompt = `A Terraform apply failed. Provide a brief overview of what went wrong, quote the key error, and give 2–3 recommended troubleshooting steps. Focus on practical next actions; do not reproduce the full log or your internal reasoning.\n\n${tail}`;
  return { prompt };
}

/** Stable storage key for the one plan or apply-error answer belonging to a run. */
export function explanationCacheKey(runId: string, kind: ExplainKind): string {
  return `${runId}-${kind === "plan" ? "plan" : "apply-error"}`;
}

/**
 * Latest cached explanation for a (run, kind). Model and prompt changes do not
 * invalidate it; callers must request an explicit refresh to replace it.
 */
export async function findExplanation(runId: string, kind: ExplainKind): Promise<StoredExplanation | undefined> {
  const rows = await db.query.runExplanations.findMany({
    where: and(eq(runExplanations.runId, runId), eq(runExplanations.kind, kind)),
    orderBy: [desc(runExplanations.createdAt)],
    limit: 1,
  });
  const row = rows[0];
  if (row === undefined) return undefined;
  return {
    id: row.id,
    runId: row.runId,
    kind: row.kind as ExplainKind,
    model: row.model,
    content: row.content,
    createdAt: row.createdAt,
  };
}

/**
 * Persist a fresh explanation for (run, kind), replacing any earlier one.
 * One row per (run, kind): the latest generation is the cache.
 */
export async function saveExplanation(
  runId: string,
  kind: ExplainKind,
  model: string,
  content: string,
): Promise<void> {
  // Delete and insert run as one unit so concurrent regenerations can never
  // leave the table without a row for (run, kind).
  await db.transaction(async (tx) => {
    await tx.delete(runExplanations).where(and(eq(runExplanations.runId, runId), eq(runExplanations.kind, kind)));
    await tx.insert(runExplanations).values({
      id: explanationCacheKey(runId, kind),
      runId,
      kind,
      model,
      content,
      // Kept populated for compatibility with the original physical column;
      // this is now the stable run/slot key, not a content hash.
      cacheKey: explanationCacheKey(runId, kind),
    });
  });
}

export type CompletionParts = Readonly<{ content: string; thinking: string }>;

/**
 * Split inline thinking tags out of accumulated text. Covers providers that
 * stream reasoning inside content as <think>...</think> or its longer
 * variants instead of a separate reasoning_content channel. Every tagged
 * reasoning segment is removed; content before, between, and after segments
 * stays content.
 */
export function splitInlineThinking(raw: string): CompletionParts {
  const openingPattern = /<(think|thinking|reasoning)>/gi;
  const thinkingParts: string[] = [];
  const contentParts: string[] = [];
  let cursor = 0;
  for (;;) {
    openingPattern.lastIndex = cursor;
    const opening = openingPattern.exec(raw);
    if (opening === null) {
      contentParts.push(raw.slice(cursor));
      break;
    }
    contentParts.push(raw.slice(cursor, opening.index));
    const thinkingStart = opening.index + opening[0].length;
    const tagName = opening[1] ?? "thinking";
    const closing = new RegExp(`</${tagName}>`, "i").exec(raw.slice(thinkingStart));
    if (closing === null) {
      thinkingParts.push(raw.slice(thinkingStart));
      break;
    }
    thinkingParts.push(raw.slice(thinkingStart, thinkingStart + closing.index));
    cursor = thinkingStart + closing.index + closing[0].length;
  }
  return { content: contentParts.join(""), thinking: thinkingParts.join("") };
}

/**
 * Common upstream request builder. `stream: true` asks the provider for an
 * SSE response; providers that ignore the flag and return plain JSON are
 * handled by the caller via content-type sniffing.
 */
export function upstreamRequest(settings: Readonly<Record<string, unknown>>, prompt: string, stream: boolean): Request {
  const baseUrl = settings["base-url"] as string;
  const endpointUrl = `${baseUrl.replace(/\/+$/, "")}/chat/completions`;
  const model = settings.model as string;
  const apiKey = typeof settings["api-key"] === "string" && settings["api-key"] !== "" ? settings["api-key"] : undefined;
  const reasoningEffort = configuredReasoningEffort(settings["reasoning-effort"]);
  const provider = typeof settings.provider === "string" ? settings.provider.toLowerCase() : "";
  const reasoningOptions = reasoningEffort === null
    ? {}
    : provider === "openrouter"
      ? { reasoning: { effort: reasoningEffort } }
      : { reasoning_effort: reasoningEffort };
  return new Request(endpointUrl, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      ...(apiKey !== undefined ? { authorization: `Bearer ${apiKey}` } : {}),
    },
    body: JSON.stringify({ model, messages: [{ role: "user", content: prompt }], ...reasoningOptions, stream }),
  });
}

function reasoningFromMessage(message: Readonly<Record<string, unknown>> | undefined): string {
  const reasoningContent = message?.reasoning_content;
  const reasoning = message?.reasoning;
  if (typeof reasoningContent === "string" && reasoningContent !== "") return reasoningContent;
  if (typeof reasoning === "string" && reasoning !== "") return reasoning;
  if (typeof reasoning === "object" && reasoning !== null) {
    const raw = JSON.stringify(reasoning);
    if (raw !== undefined && raw !== "") return raw;
  }
  return "";
}

/** Non-streaming completion parse: answer content plus transient reasoning. */
export function parseCompletionBody(parsed: unknown): CompletionParts {
  const choices = (parsed as Readonly<{ choices?: readonly Readonly<{ message?: Readonly<Record<string, unknown>> }>[] }>)?.choices;
  const message = choices?.[0]?.message;
  const contentValue = message?.content;
  let content = typeof contentValue === "string" ? contentValue : "";
  let thinking = reasoningFromMessage(message);
  const split = splitInlineThinking(content);
  content = split.content;
  if (split.thinking !== "") thinking = thinking === "" ? split.thinking : `${thinking}\n${split.thinking}`;
  return { content, thinking };
}

/**
 * Throttle a raw upstream SSE stream into (reasoning, content) channels,
 * covering the two mainstream OpenAI-compatible conventions:
 *   - delta.reasoning_content (DeepSeek and its clones)
 *   - delta.reasoning (OpenAI-style reasoning models)
 * Inline <think> tags inside delta.content are split into the thinking
 * channel while the stream is read, including tags split across chunks.
 */
export async function forEachUpstreamDelta(
  upstream: Readonly<Response>,
  onDelta: (channel: "thinking" | "content", text: string) => void | Promise<void>,
  onChunk?: () => void,
): Promise<void> {
  if (upstream.body === null) return;
  const reader = upstream.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let inlineContentBuffer = "";
  let inlineThinking = false;
  const emitInlineContent = async (text: string): Promise<void> => {
    inlineContentBuffer += text;
    for (;;) {
      const tag = (inlineThinking ? /<\/(think|thinking|reasoning)>/i : /<(think|thinking|reasoning)>/i).exec(inlineContentBuffer);
      if (tag === null) {
        const safeLength = Math.max(0, inlineContentBuffer.length - "</reasoning>".length);
        if (safeLength === 0) return;
        const safe = inlineContentBuffer.slice(0, safeLength);
        inlineContentBuffer = inlineContentBuffer.slice(safeLength);
        await onDelta(inlineThinking ? "thinking" : "content", safe);
        continue;
      }
      const before = inlineContentBuffer.slice(0, tag.index);
      if (before !== "") await onDelta(inlineThinking ? "thinking" : "content", before);
      inlineContentBuffer = inlineContentBuffer.slice(tag.index + tag[0].length);
      inlineThinking = !inlineThinking;
    }
  };
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    onChunk?.();
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed.startsWith("data:")) continue;
      const payload = trimmed.slice(5).trim();
      if (payload === "" || payload === "[DONE]") continue;
      let chunk: unknown;
      try {
        chunk = JSON.parse(payload);
      } catch {
        continue;
      }
      const delta = (chunk as Readonly<{ choices?: readonly Readonly<{ delta?: Readonly<Record<string, unknown>> }>[] }>)?.choices?.[0]?.delta;
      if (delta === undefined) continue;
      const content = delta.content;
      if (typeof content === "string" && content !== "") await emitInlineContent(content);
      const reasoningContent = delta.reasoning_content;
      const reasoning = delta.reasoning;
      const thinkingPart = typeof reasoningContent === "string" && reasoningContent !== ""
        ? reasoningContent
        : typeof reasoning === "string" && reasoning !== ""
          ? reasoning
          : "";
      if (thinkingPart !== "") await onDelta("thinking", thinkingPart);
    }
  }
  if (inlineContentBuffer !== "") {
    await onDelta(inlineThinking ? "thinking" : "content", inlineContentBuffer);
  }
}

/**
 * Shared upstream fetch with an idle timeout that stays armed for the whole
 * exchange, including body consumption. `tick` resets the deadline after each
 * chunk of activity, so a provider that answers headers and then stalls is
 * still aborted after EXPLAIN_TIMEOUT_MS of silence. Errors thrown by
 * `consume` propagate unwrapped; only the fetch itself is labeled
 * "endpoint unreachable".
 */
export async function fetchUpstream<T>(
  settings: Readonly<Record<string, unknown>>,
  prompt: string,
  stream: boolean,
  signal: Readonly<AbortSignal> | undefined,
  consume: (upstream: Readonly<Response>, tick: () => void) => Promise<T>,
): Promise<T> {
  const controller = new AbortController();
  const abortWithTimeout = (): void => { controller.abort(new Error("request timed out")); };
  let deadline = setTimeout(abortWithTimeout, EXPLAIN_TIMEOUT_MS);
  const tick = (): void => {
    clearTimeout(deadline);
    deadline = setTimeout(abortWithTimeout, EXPLAIN_TIMEOUT_MS);
  };
  const onExternalAbort = (): void => { controller.abort(); };
  signal?.addEventListener("abort", onExternalAbort, { once: true });
  try {
    let upstream: Readonly<Response>;
    try {
      upstream = await fetch(upstreamRequest(settings, prompt, stream), { signal: controller.signal });
    } catch (error: unknown) {
      throw new Error(`Plan explainer endpoint unreachable: ${error instanceof Error ? error.message : String(error)}`, { cause: error });
    }
    tick();
    return await consume(upstream, tick);
  } finally {
    clearTimeout(deadline);
    signal?.removeEventListener("abort", onExternalAbort);
  }
}

/** Standard JSON error envelope used by the explain routes. */
export function explainError(status: number, title: string, detail: string): Readonly<{ status: number; body: unknown }> {
  return { status, body: { errors: [{ status: String(status), title, detail }] } };
}

/** @public Intentional surface: benchmark/test hook or cross-module API. */
export { log };
