/* eslint-disable */
// AUTO-GENERATED by scripts/generate-schema-selector.ts — DO NOT EDIT.
// Dialect selector: sqlite-core tables are canonical (see schema-sqlite.ts);
// when the postgres backend is active, the pg tables built by pg-convert.ts
// are re-exported under the same names. Types always come from the sqlite
// definitions, so call sites are dialect-agnostic by construction.
import * as sqliteSchema from "./schema-sqlite";
import { buildPgSchema } from "./pg-convert";
import { resolveDatabaseConfig } from "../lib/boot-config";
import { join, resolve } from "node:path";

// import.meta is undefined under drizzle-kit's CJS loader; fall back to
// process.cwd() so `drizzle-kit generate` can load the selector. The path
// only feeds the STORAGE_DIR default and driver detection, so cwd is fine.
const moduleDir = typeof import.meta?.dir === "string" && import.meta.dir !== ""
  ? import.meta.dir
  : process.cwd();
const storageDir = resolve(process.env.STORAGE_DIR ?? join(moduleDir, "../../storage"));
const activeDriver = resolveDatabaseConfig(process.env, storageDir).driver;
// Built lazily: constructing the pg mirror walks every sqlite table object,
// which is wasted work on the sqlite path and can throw on exotic schema
// constructs the mirror does not understand.
const pgTables = activeDriver === "postgres" ? buildPgSchema(sqliteSchema) : null;

const dbNameOf = (table: object): string =>
  String((table as Record<PropertyKey, unknown>)[Symbol.for("drizzle:Name")]);

export const adminGeneralSettings: typeof sqliteSchema.adminGeneralSettings = pgTables === null
  ? sqliteSchema.adminGeneralSettings
  : (pgTables[dbNameOf(sqliteSchema.adminGeneralSettings)] as unknown as typeof sqliteSchema.adminGeneralSettings);

export const adminOpaVersions: typeof sqliteSchema.adminOpaVersions = pgTables === null
  ? sqliteSchema.adminOpaVersions
  : (pgTables[dbNameOf(sqliteSchema.adminOpaVersions)] as unknown as typeof sqliteSchema.adminOpaVersions);

export const adminSentinelVersions: typeof sqliteSchema.adminSentinelVersions = pgTables === null
  ? sqliteSchema.adminSentinelVersions
  : (pgTables[dbNameOf(sqliteSchema.adminSentinelVersions)] as unknown as typeof sqliteSchema.adminSentinelVersions);

export const adminSettings: typeof sqliteSchema.adminSettings = pgTables === null
  ? sqliteSchema.adminSettings
  : (pgTables[dbNameOf(sqliteSchema.adminSettings)] as unknown as typeof sqliteSchema.adminSettings);

export const adminTerraformVersions: typeof sqliteSchema.adminTerraformVersions = pgTables === null
  ? sqliteSchema.adminTerraformVersions
  : (pgTables[dbNameOf(sqliteSchema.adminTerraformVersions)] as unknown as typeof sqliteSchema.adminTerraformVersions);

export const agentForwardedRequests: typeof sqliteSchema.agentForwardedRequests = pgTables === null
  ? sqliteSchema.agentForwardedRequests
  : (pgTables[dbNameOf(sqliteSchema.agentForwardedRequests)] as unknown as typeof sqliteSchema.agentForwardedRequests);

export const agentJobs: typeof sqliteSchema.agentJobs = pgTables === null
  ? sqliteSchema.agentJobs
  : (pgTables[dbNameOf(sqliteSchema.agentJobs)] as unknown as typeof sqliteSchema.agentJobs);

export const agentPoolAllowedProjects: typeof sqliteSchema.agentPoolAllowedProjects = pgTables === null
  ? sqliteSchema.agentPoolAllowedProjects
  : (pgTables[dbNameOf(sqliteSchema.agentPoolAllowedProjects)] as unknown as typeof sqliteSchema.agentPoolAllowedProjects);

export const agentPoolAllowedWorkspaces: typeof sqliteSchema.agentPoolAllowedWorkspaces = pgTables === null
  ? sqliteSchema.agentPoolAllowedWorkspaces
  : (pgTables[dbNameOf(sqliteSchema.agentPoolAllowedWorkspaces)] as unknown as typeof sqliteSchema.agentPoolAllowedWorkspaces);

export const agentPoolExcludedWorkspaces: typeof sqliteSchema.agentPoolExcludedWorkspaces = pgTables === null
  ? sqliteSchema.agentPoolExcludedWorkspaces
  : (pgTables[dbNameOf(sqliteSchema.agentPoolExcludedWorkspaces)] as unknown as typeof sqliteSchema.agentPoolExcludedWorkspaces);

export const agentPoolTokens: typeof sqliteSchema.agentPoolTokens = pgTables === null
  ? sqliteSchema.agentPoolTokens
  : (pgTables[dbNameOf(sqliteSchema.agentPoolTokens)] as unknown as typeof sqliteSchema.agentPoolTokens);

export const agentPools: typeof sqliteSchema.agentPools = pgTables === null
  ? sqliteSchema.agentPools
  : (pgTables[dbNameOf(sqliteSchema.agentPools)] as unknown as typeof sqliteSchema.agentPools);

export const agents: typeof sqliteSchema.agents = pgTables === null
  ? sqliteSchema.agents
  : (pgTables[dbNameOf(sqliteSchema.agents)] as unknown as typeof sqliteSchema.agents);

export const apiTokens: typeof sqliteSchema.apiTokens = pgTables === null
  ? sqliteSchema.apiTokens
  : (pgTables[dbNameOf(sqliteSchema.apiTokens)] as unknown as typeof sqliteSchema.apiTokens);

export const assessmentCheckResults: typeof sqliteSchema.assessmentCheckResults = pgTables === null
  ? sqliteSchema.assessmentCheckResults
  : (pgTables[dbNameOf(sqliteSchema.assessmentCheckResults)] as unknown as typeof sqliteSchema.assessmentCheckResults);

export const assessmentResults: typeof sqliteSchema.assessmentResults = pgTables === null
  ? sqliteSchema.assessmentResults
  : (pgTables[dbNameOf(sqliteSchema.assessmentResults)] as unknown as typeof sqliteSchema.assessmentResults);

export const auditLogs: typeof sqliteSchema.auditLogs = pgTables === null
  ? sqliteSchema.auditLogs
  : (pgTables[dbNameOf(sqliteSchema.auditLogs)] as unknown as typeof sqliteSchema.auditLogs);

export const changeRequests: typeof sqliteSchema.changeRequests = pgTables === null
  ? sqliteSchema.changeRequests
  : (pgTables[dbNameOf(sqliteSchema.changeRequests)] as unknown as typeof sqliteSchema.changeRequests);

export const cidrRangeListAgentPools: typeof sqliteSchema.cidrRangeListAgentPools = pgTables === null
  ? sqliteSchema.cidrRangeListAgentPools
  : (pgTables[dbNameOf(sqliteSchema.cidrRangeListAgentPools)] as unknown as typeof sqliteSchema.cidrRangeListAgentPools);

export const cidrRangeLists: typeof sqliteSchema.cidrRangeLists = pgTables === null
  ? sqliteSchema.cidrRangeLists
  : (pgTables[dbNameOf(sqliteSchema.cidrRangeLists)] as unknown as typeof sqliteSchema.cidrRangeLists);

export const cidrRanges: typeof sqliteSchema.cidrRanges = pgTables === null
  ? sqliteSchema.cidrRanges
  : (pgTables[dbNameOf(sqliteSchema.cidrRanges)] as unknown as typeof sqliteSchema.cidrRanges);

export const configurationVersions: typeof sqliteSchema.configurationVersions = pgTables === null
  ? sqliteSchema.configurationVersions
  : (pgTables[dbNameOf(sqliteSchema.configurationVersions)] as unknown as typeof sqliteSchema.configurationVersions);

export const controlPlaneNodes: typeof sqliteSchema.controlPlaneNodes = pgTables === null
  ? sqliteSchema.controlPlaneNodes
  : (pgTables[dbNameOf(sqliteSchema.controlPlaneNodes)] as unknown as typeof sqliteSchema.controlPlaneNodes);

export const dataRetentionPolicies: typeof sqliteSchema.dataRetentionPolicies = pgTables === null
  ? sqliteSchema.dataRetentionPolicies
  : (pgTables[dbNameOf(sqliteSchema.dataRetentionPolicies)] as unknown as typeof sqliteSchema.dataRetentionPolicies);

export const durableJobs: typeof sqliteSchema.durableJobs = pgTables === null
  ? sqliteSchema.durableJobs
  : (pgTables[dbNameOf(sqliteSchema.durableJobs)] as unknown as typeof sqliteSchema.durableJobs);

export const explorerCatalogItems: typeof sqliteSchema.explorerCatalogItems = pgTables === null
  ? sqliteSchema.explorerCatalogItems
  : (pgTables[dbNameOf(sqliteSchema.explorerCatalogItems)] as unknown as typeof sqliteSchema.explorerCatalogItems);

export const explorerCatalogMemberships: typeof sqliteSchema.explorerCatalogMemberships = pgTables === null
  ? sqliteSchema.explorerCatalogMemberships
  : (pgTables[dbNameOf(sqliteSchema.explorerCatalogMemberships)] as unknown as typeof sqliteSchema.explorerCatalogMemberships);

export const explorerSavedQueries: typeof sqliteSchema.explorerSavedQueries = pgTables === null
  ? sqliteSchema.explorerSavedQueries
  : (pgTables[dbNameOf(sqliteSchema.explorerSavedQueries)] as unknown as typeof sqliteSchema.explorerSavedQueries);

export const explorerWorkspaceInventory: typeof sqliteSchema.explorerWorkspaceInventory = pgTables === null
  ? sqliteSchema.explorerWorkspaceInventory
  : (pgTables[dbNameOf(sqliteSchema.explorerWorkspaceInventory)] as unknown as typeof sqliteSchema.explorerWorkspaceInventory);

export const githubAppInstallations: typeof sqliteSchema.githubAppInstallations = pgTables === null
  ? sqliteSchema.githubAppInstallations
  : (pgTables[dbNameOf(sqliteSchema.githubAppInstallations)] as unknown as typeof sqliteSchema.githubAppInstallations);

export const githubWebhookDeliveries: typeof sqliteSchema.githubWebhookDeliveries = pgTables === null
  ? sqliteSchema.githubWebhookDeliveries
  : (pgTables[dbNameOf(sqliteSchema.githubWebhookDeliveries)] as unknown as typeof sqliteSchema.githubWebhookDeliveries);

export const hyokConfigurations: typeof sqliteSchema.hyokConfigurations = pgTables === null
  ? sqliteSchema.hyokConfigurations
  : (pgTables[dbNameOf(sqliteSchema.hyokConfigurations)] as unknown as typeof sqliteSchema.hyokConfigurations);

export const hyokCustomerKeyVersions: typeof sqliteSchema.hyokCustomerKeyVersions = pgTables === null
  ? sqliteSchema.hyokCustomerKeyVersions
  : (pgTables[dbNameOf(sqliteSchema.hyokCustomerKeyVersions)] as unknown as typeof sqliteSchema.hyokCustomerKeyVersions);

export const locks: typeof sqliteSchema.locks = pgTables === null
  ? sqliteSchema.locks
  : (pgTables[dbNameOf(sqliteSchema.locks)] as unknown as typeof sqliteSchema.locks);

export const logs: typeof sqliteSchema.logs = pgTables === null
  ? sqliteSchema.logs
  : (pgTables[dbNameOf(sqliteSchema.logs)] as unknown as typeof sqliteSchema.logs);

export const moduleTestConfigurationVersions: typeof sqliteSchema.moduleTestConfigurationVersions = pgTables === null
  ? sqliteSchema.moduleTestConfigurationVersions
  : (pgTables[dbNameOf(sqliteSchema.moduleTestConfigurationVersions)] as unknown as typeof sqliteSchema.moduleTestConfigurationVersions);

export const moduleTestConfigurations: typeof sqliteSchema.moduleTestConfigurations = pgTables === null
  ? sqliteSchema.moduleTestConfigurations
  : (pgTables[dbNameOf(sqliteSchema.moduleTestConfigurations)] as unknown as typeof sqliteSchema.moduleTestConfigurations);

export const moduleTestResults: typeof sqliteSchema.moduleTestResults = pgTables === null
  ? sqliteSchema.moduleTestResults
  : (pgTables[dbNameOf(sqliteSchema.moduleTestResults)] as unknown as typeof sqliteSchema.moduleTestResults);

export const moduleTestRuns: typeof sqliteSchema.moduleTestRuns = pgTables === null
  ? sqliteSchema.moduleTestRuns
  : (pgTables[dbNameOf(sqliteSchema.moduleTestRuns)] as unknown as typeof sqliteSchema.moduleTestRuns);

export const noCodeModules: typeof sqliteSchema.noCodeModules = pgTables === null
  ? sqliteSchema.noCodeModules
  : (pgTables[dbNameOf(sqliteSchema.noCodeModules)] as unknown as typeof sqliteSchema.noCodeModules);

export const noCodeVariableOptions: typeof sqliteSchema.noCodeVariableOptions = pgTables === null
  ? sqliteSchema.noCodeVariableOptions
  : (pgTables[dbNameOf(sqliteSchema.noCodeVariableOptions)] as unknown as typeof sqliteSchema.noCodeVariableOptions);

export const noCodeWorkspaceConfigurations: typeof sqliteSchema.noCodeWorkspaceConfigurations = pgTables === null
  ? sqliteSchema.noCodeWorkspaceConfigurations
  : (pgTables[dbNameOf(sqliteSchema.noCodeWorkspaceConfigurations)] as unknown as typeof sqliteSchema.noCodeWorkspaceConfigurations);

export const notificationConfigurationWorkspaceExclusions: typeof sqliteSchema.notificationConfigurationWorkspaceExclusions = pgTables === null
  ? sqliteSchema.notificationConfigurationWorkspaceExclusions
  : (pgTables[dbNameOf(sqliteSchema.notificationConfigurationWorkspaceExclusions)] as unknown as typeof sqliteSchema.notificationConfigurationWorkspaceExclusions);

export const notificationConfigurations: typeof sqliteSchema.notificationConfigurations = pgTables === null
  ? sqliteSchema.notificationConfigurations
  : (pgTables[dbNameOf(sqliteSchema.notificationConfigurations)] as unknown as typeof sqliteSchema.notificationConfigurations);

export const notificationWorkspaceCounters: typeof sqliteSchema.notificationWorkspaceCounters = pgTables === null
  ? sqliteSchema.notificationWorkspaceCounters
  : (pgTables[dbNameOf(sqliteSchema.notificationWorkspaceCounters)] as unknown as typeof sqliteSchema.notificationWorkspaceCounters);

export const oauthClientProjects: typeof sqliteSchema.oauthClientProjects = pgTables === null
  ? sqliteSchema.oauthClientProjects
  : (pgTables[dbNameOf(sqliteSchema.oauthClientProjects)] as unknown as typeof sqliteSchema.oauthClientProjects);

export const oauthClients: typeof sqliteSchema.oauthClients = pgTables === null
  ? sqliteSchema.oauthClients
  : (pgTables[dbNameOf(sqliteSchema.oauthClients)] as unknown as typeof sqliteSchema.oauthClients);

export const oauthDeviceCodes: typeof sqliteSchema.oauthDeviceCodes = pgTables === null
  ? sqliteSchema.oauthDeviceCodes
  : (pgTables[dbNameOf(sqliteSchema.oauthDeviceCodes)] as unknown as typeof sqliteSchema.oauthDeviceCodes);

export const oauthHandshakeStates: typeof sqliteSchema.oauthHandshakeStates = pgTables === null
  ? sqliteSchema.oauthHandshakeStates
  : (pgTables[dbNameOf(sqliteSchema.oauthHandshakeStates)] as unknown as typeof sqliteSchema.oauthHandshakeStates);

export const oauthTokens: typeof sqliteSchema.oauthTokens = pgTables === null
  ? sqliteSchema.oauthTokens
  : (pgTables[dbNameOf(sqliteSchema.oauthTokens)] as unknown as typeof sqliteSchema.oauthTokens);

export const oidcConfigs: typeof sqliteSchema.oidcConfigs = pgTables === null
  ? sqliteSchema.oidcConfigs
  : (pgTables[dbNameOf(sqliteSchema.oidcConfigs)] as unknown as typeof sqliteSchema.oidcConfigs);

export const orgTokenTTLPolicies: typeof sqliteSchema.orgTokenTTLPolicies = pgTables === null
  ? sqliteSchema.orgTokenTTLPolicies
  : (pgTables[dbNameOf(sqliteSchema.orgTokenTTLPolicies)] as unknown as typeof sqliteSchema.orgTokenTTLPolicies);

export const organizationDataRetentionPolicies: typeof sqliteSchema.organizationDataRetentionPolicies = pgTables === null
  ? sqliteSchema.organizationDataRetentionPolicies
  : (pgTables[dbNameOf(sqliteSchema.organizationDataRetentionPolicies)] as unknown as typeof sqliteSchema.organizationDataRetentionPolicies);

export const organizationMembershipRoles: typeof sqliteSchema.organizationMembershipRoles = pgTables === null
  ? sqliteSchema.organizationMembershipRoles
  : (pgTables[dbNameOf(sqliteSchema.organizationMembershipRoles)] as unknown as typeof sqliteSchema.organizationMembershipRoles);

export const organizationMemberships: typeof sqliteSchema.organizationMemberships = pgTables === null
  ? sqliteSchema.organizationMemberships
  : (pgTables[dbNameOf(sqliteSchema.organizationMemberships)] as unknown as typeof sqliteSchema.organizationMemberships);

export const organizationRoles: typeof sqliteSchema.organizationRoles = pgTables === null
  ? sqliteSchema.organizationRoles
  : (pgTables[dbNameOf(sqliteSchema.organizationRoles)] as unknown as typeof sqliteSchema.organizationRoles);

export const organizations: typeof sqliteSchema.organizations = pgTables === null
  ? sqliteSchema.organizations
  : (pgTables[dbNameOf(sqliteSchema.organizations)] as unknown as typeof sqliteSchema.organizations);

export const planExports: typeof sqliteSchema.planExports = pgTables === null
  ? sqliteSchema.planExports
  : (pgTables[dbNameOf(sqliteSchema.planExports)] as unknown as typeof sqliteSchema.planExports);

export const policies: typeof sqliteSchema.policies = pgTables === null
  ? sqliteSchema.policies
  : (pgTables[dbNameOf(sqliteSchema.policies)] as unknown as typeof sqliteSchema.policies);

export const policyChecks: typeof sqliteSchema.policyChecks = pgTables === null
  ? sqliteSchema.policyChecks
  : (pgTables[dbNameOf(sqliteSchema.policyChecks)] as unknown as typeof sqliteSchema.policyChecks);

export const policyEvaluations: typeof sqliteSchema.policyEvaluations = pgTables === null
  ? sqliteSchema.policyEvaluations
  : (pgTables[dbNameOf(sqliteSchema.policyEvaluations)] as unknown as typeof sqliteSchema.policyEvaluations);

export const policySetExclusions: typeof sqliteSchema.policySetExclusions = pgTables === null
  ? sqliteSchema.policySetExclusions
  : (pgTables[dbNameOf(sqliteSchema.policySetExclusions)] as unknown as typeof sqliteSchema.policySetExclusions);

export const policySetOutcomes: typeof sqliteSchema.policySetOutcomes = pgTables === null
  ? sqliteSchema.policySetOutcomes
  : (pgTables[dbNameOf(sqliteSchema.policySetOutcomes)] as unknown as typeof sqliteSchema.policySetOutcomes);

export const policySetParameters: typeof sqliteSchema.policySetParameters = pgTables === null
  ? sqliteSchema.policySetParameters
  : (pgTables[dbNameOf(sqliteSchema.policySetParameters)] as unknown as typeof sqliteSchema.policySetParameters);

export const policySetProjectExclusions: typeof sqliteSchema.policySetProjectExclusions = pgTables === null
  ? sqliteSchema.policySetProjectExclusions
  : (pgTables[dbNameOf(sqliteSchema.policySetProjectExclusions)] as unknown as typeof sqliteSchema.policySetProjectExclusions);

export const policySetProjects: typeof sqliteSchema.policySetProjects = pgTables === null
  ? sqliteSchema.policySetProjects
  : (pgTables[dbNameOf(sqliteSchema.policySetProjects)] as unknown as typeof sqliteSchema.policySetProjects);

export const policySetTagSelectors: typeof sqliteSchema.policySetTagSelectors = pgTables === null
  ? sqliteSchema.policySetTagSelectors
  : (pgTables[dbNameOf(sqliteSchema.policySetTagSelectors)] as unknown as typeof sqliteSchema.policySetTagSelectors);

export const policySetVersions: typeof sqliteSchema.policySetVersions = pgTables === null
  ? sqliteSchema.policySetVersions
  : (pgTables[dbNameOf(sqliteSchema.policySetVersions)] as unknown as typeof sqliteSchema.policySetVersions);

export const policySetWorkspaces: typeof sqliteSchema.policySetWorkspaces = pgTables === null
  ? sqliteSchema.policySetWorkspaces
  : (pgTables[dbNameOf(sqliteSchema.policySetWorkspaces)] as unknown as typeof sqliteSchema.policySetWorkspaces);

export const policySets: typeof sqliteSchema.policySets = pgTables === null
  ? sqliteSchema.policySets
  : (pgTables[dbNameOf(sqliteSchema.policySets)] as unknown as typeof sqliteSchema.policySets);

export const projectTags: typeof sqliteSchema.projectTags = pgTables === null
  ? sqliteSchema.projectTags
  : (pgTables[dbNameOf(sqliteSchema.projectTags)] as unknown as typeof sqliteSchema.projectTags);

export const projects: typeof sqliteSchema.projects = pgTables === null
  ? sqliteSchema.projects
  : (pgTables[dbNameOf(sqliteSchema.projects)] as unknown as typeof sqliteSchema.projects);

export const providerSets: typeof sqliteSchema.providerSets = pgTables === null
  ? sqliteSchema.providerSets
  : (pgTables[dbNameOf(sqliteSchema.providerSets)] as unknown as typeof sqliteSchema.providerSets);

export const queryRuns: typeof sqliteSchema.queryRuns = pgTables === null
  ? sqliteSchema.queryRuns
  : (pgTables[dbNameOf(sqliteSchema.queryRuns)] as unknown as typeof sqliteSchema.queryRuns);

export const refreshSessions: typeof sqliteSchema.refreshSessions = pgTables === null
  ? sqliteSchema.refreshSessions
  : (pgTables[dbNameOf(sqliteSchema.refreshSessions)] as unknown as typeof sqliteSchema.refreshSessions);

export const registryGpgKeys: typeof sqliteSchema.registryGpgKeys = pgTables === null
  ? sqliteSchema.registryGpgKeys
  : (pgTables[dbNameOf(sqliteSchema.registryGpgKeys)] as unknown as typeof sqliteSchema.registryGpgKeys);

export const registryModuleVersions: typeof sqliteSchema.registryModuleVersions = pgTables === null
  ? sqliteSchema.registryModuleVersions
  : (pgTables[dbNameOf(sqliteSchema.registryModuleVersions)] as unknown as typeof sqliteSchema.registryModuleVersions);

export const registryModules: typeof sqliteSchema.registryModules = pgTables === null
  ? sqliteSchema.registryModules
  : (pgTables[dbNameOf(sqliteSchema.registryModules)] as unknown as typeof sqliteSchema.registryModules);

export const registryPartnerships: typeof sqliteSchema.registryPartnerships = pgTables === null
  ? sqliteSchema.registryPartnerships
  : (pgTables[dbNameOf(sqliteSchema.registryPartnerships)] as unknown as typeof sqliteSchema.registryPartnerships);

export const registryProviderPlatforms: typeof sqliteSchema.registryProviderPlatforms = pgTables === null
  ? sqliteSchema.registryProviderPlatforms
  : (pgTables[dbNameOf(sqliteSchema.registryProviderPlatforms)] as unknown as typeof sqliteSchema.registryProviderPlatforms);

export const registryProviderVersions: typeof sqliteSchema.registryProviderVersions = pgTables === null
  ? sqliteSchema.registryProviderVersions
  : (pgTables[dbNameOf(sqliteSchema.registryProviderVersions)] as unknown as typeof sqliteSchema.registryProviderVersions);

export const registryProviders: typeof sqliteSchema.registryProviders = pgTables === null
  ? sqliteSchema.registryProviders
  : (pgTables[dbNameOf(sqliteSchema.registryProviders)] as unknown as typeof sqliteSchema.registryProviders);

export const registrySyncLeases: typeof sqliteSchema.registrySyncLeases = pgTables === null
  ? sqliteSchema.registrySyncLeases
  : (pgTables[dbNameOf(sqliteSchema.registrySyncLeases)] as unknown as typeof sqliteSchema.registrySyncLeases);

export const remoteStateConsumers: typeof sqliteSchema.remoteStateConsumers = pgTables === null
  ? sqliteSchema.remoteStateConsumers
  : (pgTables[dbNameOf(sqliteSchema.remoteStateConsumers)] as unknown as typeof sqliteSchema.remoteStateConsumers);

export const reservedTagKeys: typeof sqliteSchema.reservedTagKeys = pgTables === null
  ? sqliteSchema.reservedTagKeys
  : (pgTables[dbNameOf(sqliteSchema.reservedTagKeys)] as unknown as typeof sqliteSchema.reservedTagKeys);

export const runComments: typeof sqliteSchema.runComments = pgTables === null
  ? sqliteSchema.runComments
  : (pgTables[dbNameOf(sqliteSchema.runComments)] as unknown as typeof sqliteSchema.runComments);

export const runExplanations: typeof sqliteSchema.runExplanations = pgTables === null
  ? sqliteSchema.runExplanations
  : (pgTables[dbNameOf(sqliteSchema.runExplanations)] as unknown as typeof sqliteSchema.runExplanations);

export const runTaskResults: typeof sqliteSchema.runTaskResults = pgTables === null
  ? sqliteSchema.runTaskResults
  : (pgTables[dbNameOf(sqliteSchema.runTaskResults)] as unknown as typeof sqliteSchema.runTaskResults);

export const runTasks: typeof sqliteSchema.runTasks = pgTables === null
  ? sqliteSchema.runTasks
  : (pgTables[dbNameOf(sqliteSchema.runTasks)] as unknown as typeof sqliteSchema.runTasks);

export const runTokens: typeof sqliteSchema.runTokens = pgTables === null
  ? sqliteSchema.runTokens
  : (pgTables[dbNameOf(sqliteSchema.runTokens)] as unknown as typeof sqliteSchema.runTokens);

export const runTriggers: typeof sqliteSchema.runTriggers = pgTables === null
  ? sqliteSchema.runTriggers
  : (pgTables[dbNameOf(sqliteSchema.runTriggers)] as unknown as typeof sqliteSchema.runTriggers);

export const runs: typeof sqliteSchema.runs = pgTables === null
  ? sqliteSchema.runs
  : (pgTables[dbNameOf(sqliteSchema.runs)] as unknown as typeof sqliteSchema.runs);

export const samlSettings: typeof sqliteSchema.samlSettings = pgTables === null
  ? sqliteSchema.samlSettings
  : (pgTables[dbNameOf(sqliteSchema.samlSettings)] as unknown as typeof sqliteSchema.samlSettings);

export const scimGroupMemberships: typeof sqliteSchema.scimGroupMemberships = pgTables === null
  ? sqliteSchema.scimGroupMemberships
  : (pgTables[dbNameOf(sqliteSchema.scimGroupMemberships)] as unknown as typeof sqliteSchema.scimGroupMemberships);

export const scimGroups: typeof sqliteSchema.scimGroups = pgTables === null
  ? sqliteSchema.scimGroups
  : (pgTables[dbNameOf(sqliteSchema.scimGroups)] as unknown as typeof sqliteSchema.scimGroups);

export const scimSettings: typeof sqliteSchema.scimSettings = pgTables === null
  ? sqliteSchema.scimSettings
  : (pgTables[dbNameOf(sqliteSchema.scimSettings)] as unknown as typeof sqliteSchema.scimSettings);

export const scimTokens: typeof sqliteSchema.scimTokens = pgTables === null
  ? sqliteSchema.scimTokens
  : (pgTables[dbNameOf(sqliteSchema.scimTokens)] as unknown as typeof sqliteSchema.scimTokens);

export const scimUserIdentities: typeof sqliteSchema.scimUserIdentities = pgTables === null
  ? sqliteSchema.scimUserIdentities
  : (pgTables[dbNameOf(sqliteSchema.scimUserIdentities)] as unknown as typeof sqliteSchema.scimUserIdentities);

export const siteDataRetentionPolicies: typeof sqliteSchema.siteDataRetentionPolicies = pgTables === null
  ? sqliteSchema.siteDataRetentionPolicies
  : (pgTables[dbNameOf(sqliteSchema.siteDataRetentionPolicies)] as unknown as typeof sqliteSchema.siteDataRetentionPolicies);

export const sshKeys: typeof sqliteSchema.sshKeys = pgTables === null
  ? sqliteSchema.sshKeys
  : (pgTables[dbNameOf(sqliteSchema.sshKeys)] as unknown as typeof sqliteSchema.sshKeys);

export const ssoChallenges: typeof sqliteSchema.ssoChallenges = pgTables === null
  ? sqliteSchema.ssoChallenges
  : (pgTables[dbNameOf(sqliteSchema.ssoChallenges)] as unknown as typeof sqliteSchema.ssoChallenges);

export const stackAgentJobs: typeof sqliteSchema.stackAgentJobs = pgTables === null
  ? sqliteSchema.stackAgentJobs
  : (pgTables[dbNameOf(sqliteSchema.stackAgentJobs)] as unknown as typeof sqliteSchema.stackAgentJobs);

export const stackRecords: typeof sqliteSchema.stackRecords = pgTables === null
  ? sqliteSchema.stackRecords
  : (pgTables[dbNameOf(sqliteSchema.stackRecords)] as unknown as typeof sqliteSchema.stackRecords);

export const stackStateLocks: typeof sqliteSchema.stackStateLocks = pgTables === null
  ? sqliteSchema.stackStateLocks
  : (pgTables[dbNameOf(sqliteSchema.stackStateLocks)] as unknown as typeof sqliteSchema.stackStateLocks);

export const stackVariableSets: typeof sqliteSchema.stackVariableSets = pgTables === null
  ? sqliteSchema.stackVariableSets
  : (pgTables[dbNameOf(sqliteSchema.stackVariableSets)] as unknown as typeof sqliteSchema.stackVariableSets);

export const stacks: typeof sqliteSchema.stacks = pgTables === null
  ? sqliteSchema.stacks
  : (pgTables[dbNameOf(sqliteSchema.stacks)] as unknown as typeof sqliteSchema.stacks);

export const stateVersions: typeof sqliteSchema.stateVersions = pgTables === null
  ? sqliteSchema.stateVersions
  : (pgTables[dbNameOf(sqliteSchema.stateVersions)] as unknown as typeof sqliteSchema.stateVersions);

export const supportBundleRequests: typeof sqliteSchema.supportBundleRequests = pgTables === null
  ? sqliteSchema.supportBundleRequests
  : (pgTables[dbNameOf(sqliteSchema.supportBundleRequests)] as unknown as typeof sqliteSchema.supportBundleRequests);

export const systemApiTokens: typeof sqliteSchema.systemApiTokens = pgTables === null
  ? sqliteSchema.systemApiTokens
  : (pgTables[dbNameOf(sqliteSchema.systemApiTokens)] as unknown as typeof sqliteSchema.systemApiTokens);

export const taskStages: typeof sqliteSchema.taskStages = pgTables === null
  ? sqliteSchema.taskStages
  : (pgTables[dbNameOf(sqliteSchema.taskStages)] as unknown as typeof sqliteSchema.taskStages);

export const teamMemberships: typeof sqliteSchema.teamMemberships = pgTables === null
  ? sqliteSchema.teamMemberships
  : (pgTables[dbNameOf(sqliteSchema.teamMemberships)] as unknown as typeof sqliteSchema.teamMemberships);

export const teamProjects: typeof sqliteSchema.teamProjects = pgTables === null
  ? sqliteSchema.teamProjects
  : (pgTables[dbNameOf(sqliteSchema.teamProjects)] as unknown as typeof sqliteSchema.teamProjects);

export const teamScimGroupMappings: typeof sqliteSchema.teamScimGroupMappings = pgTables === null
  ? sqliteSchema.teamScimGroupMappings
  : (pgTables[dbNameOf(sqliteSchema.teamScimGroupMappings)] as unknown as typeof sqliteSchema.teamScimGroupMappings);

export const teamWorkspaces: typeof sqliteSchema.teamWorkspaces = pgTables === null
  ? sqliteSchema.teamWorkspaces
  : (pgTables[dbNameOf(sqliteSchema.teamWorkspaces)] as unknown as typeof sqliteSchema.teamWorkspaces);

export const teams: typeof sqliteSchema.teams = pgTables === null
  ? sqliteSchema.teams
  : (pgTables[dbNameOf(sqliteSchema.teams)] as unknown as typeof sqliteSchema.teams);

export const testVariables: typeof sqliteSchema.testVariables = pgTables === null
  ? sqliteSchema.testVariables
  : (pgTables[dbNameOf(sqliteSchema.testVariables)] as unknown as typeof sqliteSchema.testVariables);

export const user2FA: typeof sqliteSchema.user2FA = pgTables === null
  ? sqliteSchema.user2FA
  : (pgTables[dbNameOf(sqliteSchema.user2FA)] as unknown as typeof sqliteSchema.user2FA);

export const users: typeof sqliteSchema.users = pgTables === null
  ? sqliteSchema.users
  : (pgTables[dbNameOf(sqliteSchema.users)] as unknown as typeof sqliteSchema.users);

export const variableSetProjects: typeof sqliteSchema.variableSetProjects = pgTables === null
  ? sqliteSchema.variableSetProjects
  : (pgTables[dbNameOf(sqliteSchema.variableSetProjects)] as unknown as typeof sqliteSchema.variableSetProjects);

export const variableSetVariables: typeof sqliteSchema.variableSetVariables = pgTables === null
  ? sqliteSchema.variableSetVariables
  : (pgTables[dbNameOf(sqliteSchema.variableSetVariables)] as unknown as typeof sqliteSchema.variableSetVariables);

export const variableSetWorkspaces: typeof sqliteSchema.variableSetWorkspaces = pgTables === null
  ? sqliteSchema.variableSetWorkspaces
  : (pgTables[dbNameOf(sqliteSchema.variableSetWorkspaces)] as unknown as typeof sqliteSchema.variableSetWorkspaces);

export const variableSets: typeof sqliteSchema.variableSets = pgTables === null
  ? sqliteSchema.variableSets
  : (pgTables[dbNameOf(sqliteSchema.variableSets)] as unknown as typeof sqliteSchema.variableSets);

export const workloadIdentityKeys: typeof sqliteSchema.workloadIdentityKeys = pgTables === null
  ? sqliteSchema.workloadIdentityKeys
  : (pgTables[dbNameOf(sqliteSchema.workloadIdentityKeys)] as unknown as typeof sqliteSchema.workloadIdentityKeys);

export const workloadIdentityLeases: typeof sqliteSchema.workloadIdentityLeases = pgTables === null
  ? sqliteSchema.workloadIdentityLeases
  : (pgTables[dbNameOf(sqliteSchema.workloadIdentityLeases)] as unknown as typeof sqliteSchema.workloadIdentityLeases);

export const workloadIdentityTokens: typeof sqliteSchema.workloadIdentityTokens = pgTables === null
  ? sqliteSchema.workloadIdentityTokens
  : (pgTables[dbNameOf(sqliteSchema.workloadIdentityTokens)] as unknown as typeof sqliteSchema.workloadIdentityTokens);

export const workspaceRunTasks: typeof sqliteSchema.workspaceRunTasks = pgTables === null
  ? sqliteSchema.workspaceRunTasks
  : (pgTables[dbNameOf(sqliteSchema.workspaceRunTasks)] as unknown as typeof sqliteSchema.workspaceRunTasks);

export const workspaceTags: typeof sqliteSchema.workspaceTags = pgTables === null
  ? sqliteSchema.workspaceTags
  : (pgTables[dbNameOf(sqliteSchema.workspaceTags)] as unknown as typeof sqliteSchema.workspaceTags);

export const workspaceTransfers: typeof sqliteSchema.workspaceTransfers = pgTables === null
  ? sqliteSchema.workspaceTransfers
  : (pgTables[dbNameOf(sqliteSchema.workspaceTransfers)] as unknown as typeof sqliteSchema.workspaceTransfers);

export const workspaceVariables: typeof sqliteSchema.workspaceVariables = pgTables === null
  ? sqliteSchema.workspaceVariables
  : (pgTables[dbNameOf(sqliteSchema.workspaceVariables)] as unknown as typeof sqliteSchema.workspaceVariables);

export const workspaces: typeof sqliteSchema.workspaces = pgTables === null
  ? sqliteSchema.workspaces
  : (pgTables[dbNameOf(sqliteSchema.workspaces)] as unknown as typeof sqliteSchema.workspaces);
