// Shared admin helpers (split from routes/admin.ts).
import { db, isPostgres } from "../../db";
import { users, organizations, workspaces, runs, registryPartnerships, samlSettings, adminSettings } from "../../db/schema";
import { eq } from "drizzle-orm";
import { AvatarService } from "../../lib/avatars";
import { type Settings, getSettings, invalidateSettingsCache, normalizePlanExplainerBaseUrl } from "../../lib/settings";
import { type DeepReadonly, apiURL } from "../../lib/utils";
import { withDbLock } from "../../lib/db-lock";
import type { SetObj } from "./types";
// Static provider-surface catalog (kanban 11.18). Generated by the provider
// E2E suite and kept current with `hashicorp/tfe`; the dashboard surfaces it
// as an admin read-only endpoint instead of shipping it in the bundle.
// --- Operations settings helpers (kanban 21.2 / 21.6 / 21.8) ---------
export function usableHttpUrl(value: unknown): boolean {
  if (typeof value !== "string" || value === "") return false;
  try {
    const parsed = new URL(value);
    return (parsed.protocol === "http:" || parsed.protocol === "https:") && parsed.hostname !== "";
  } catch {
    return false;
  }
}
// Clock "HH:MM" with a real hour 0-23 and minute 0-59 (rejects 25:00 etc).
export function validClockTime(value: unknown): boolean {
  if (typeof value !== "string" || !/^\d{1,2}:\d{2}$/.test(value)) return false;
  const match = /^(\d{1,2}):(\d{2})$/.exec(value);
  if (match === null) return false;
  const hours = Number.parseInt(match[1] ?? "0", 10);
  const minutes = Number.parseInt(match[2] ?? "0", 10);
  return hours >= 0 && hours <= 23 && minutes >= 0 && minutes <= 59;
}
// Redact secrets for the admin read surface: the stored secret / API key
// are never returned once set. `*-set` booleans tell the UI a value is
// stored so it can render a masked placeholder; PATCH preserves the stored
// value when the key is omitted and clears it when explicitly null.
export async function operationsSettingsResource(): Promise<Record<string, unknown>> {
  const [approval, windows, explainer] = await Promise.all([
    getSettings("approval-webhook"),
    getSettings("maintenance-windows"),
    getSettings("plan-explainer"),
  ]);
  const approvalSafe: Record<string, unknown> = {
    ...approval,
    "secret-set": typeof approval.secret === "string" && approval.secret !== "",
  };
  delete approvalSafe.secret;
  const explainerSafe: Record<string, unknown> = {
    ...explainer,
    "base-url": normalizePlanExplainerBaseUrl(explainer["base-url"])
      ?? normalizePlanExplainerBaseUrl(explainer["endpoint-url"]),
    "api-key-set": typeof explainer["api-key"] === "string" && explainer["api-key"] !== "",
  };
  delete explainerSafe["endpoint-url"];
  delete explainerSafe["api-key"];
  return {
    id: "operations-settings",
    type: "operations-settings",
    attributes: {
      "approval-webhook": approvalSafe,
      "maintenance-windows": windows,
      "plan-explainer": explainerSafe,
    },
  };
}
export type UserItem = DeepReadonly<typeof users.$inferSelect>;
export type OrgItem = DeepReadonly<typeof organizations.$inferSelect>;
export type WsItem = DeepReadonly<typeof workspaces.$inferSelect>;
export type RunItem = DeepReadonly<typeof runs.$inferSelect>;
export type VerItem = Readonly<{
  readonly id: string;
  readonly version: string;
  readonly url: string | null;
  readonly sha: string | null;
  readonly isDefault: boolean | null;
  readonly enabled: boolean | null;
  readonly deprecated: boolean | null;
}>;
// The tfe provider reads "enabled" on Terraform/Sentinel/OPA version resources
// (defaults to true); omitting it makes the provider throw an "inconsistent
// result after apply" error, so it is surfaced on every read path.
export function versionResource(value: VerItem, type: string): Record<string, unknown> {
  return {
    id: value.id,
    type,
    attributes: {
      version: value.version,
      url: value.url,
      sha: value.sha,
      default: value.isDefault === true,
      deprecated: value.deprecated === true,
      enabled: value.enabled !== false,
    },
  };
}
export type SamlSettings = Readonly<typeof samlSettings.$inferSelect>;
export const SAML_SETTINGS_ID = "saml";
export const OIDC_SIGNING_ALGORITHMS = new Set([
  "HS256", "HS384", "HS512",
  "RS256", "RS384", "RS512",
  "ES256", "ES384", "ES512",
  "PS256", "PS384", "PS512",
]);
export const SAML_DEFAULTS = {
  id: SAML_SETTINGS_ID,
  enabled: false,
  debug: false,
  oldIdpCert: null,
  idpCert: null,
  idpEntityId: null,
  sloEndpointUrl: null,
  ssoEndpointUrl: null,
  attrUsername: "Username",
  attrEmail: "email",
  attrGroups: "MemberOf",
  attrSiteAdmin: "SiteAdmin",
  siteAdminRole: "site-admins",
  ssoApiTokenSessionTimeout: 1_209_600,
  updatedAt: 0,
} satisfies typeof samlSettings.$inferInsert;
// ponytail (resolved): the in-process queue below serializes settings writes
// within one Bun process (the original single-instance deployment model). For
// the postgres backend, which may run as multiple replicas, the operation also
// runs under a database-backed mutex (src/lib/db-lock.ts) so a concurrent
// read-modify-write on another replica cannot lose updates. SQLite stays on the
// in-process queue alone: it is the single-process deployment model, and the
// extra DB round-trip is unnecessary there.
let authSettingsQueue = Promise.resolve();
export async function withAuthSettingsLock<T>(operation: () => Promise<T>): Promise<T> {
  const previous = authSettingsQueue;
  let release!: () => void;
  authSettingsQueue = new Promise<void>((resolve): void => { release = resolve; });
  await previous;
  try {
    return isPostgres
      ? await withDbLock("auth-settings", operation)
      : await operation();
  } finally {
    release();
  }
}
export async function updateSettings(group: string, attrs: Settings): Promise<Settings> {
  const current = await getSettings(group);
  const values = { ...current };
  for (const key of Object.keys(attrs)) {
    if (attrs[key] !== undefined) values[key] = attrs[key];
  }
  await db.insert(adminSettings).values({ id: group, values, updatedAt: Date.now() }).onConflictDoUpdate({ target: adminSettings.id, set: { values, updatedAt: Date.now() } });
  invalidateSettingsCache();
  return values;
}
export function settingResource(id: string, values: Settings): Record<string, unknown> {
  return { data: { id, type: id === "settings" ? "settings" : id, attributes: values } };
}
export function oidcSettingsResource(values: Settings): Record<string, unknown> {
  const safe = { ...values };
  const clientSecret = safe["client-secret"];
  delete safe["client-secret"];
  return settingResource("oidc-settings", {
    ...safe,
    "client-secret-set": typeof clientSecret === "string" && clientSecret !== "",
  });
}
export async function currentSamlSettings(): Promise<SamlSettings> {
  const existing = await db.query.samlSettings.findFirst({ where: eq(samlSettings.id, SAML_SETTINGS_ID) });
  if (existing !== undefined) return existing;
  await db.insert(samlSettings).values(SAML_DEFAULTS).onConflictDoNothing();
  const settings = await db.query.samlSettings.findFirst({ where: eq(samlSettings.id, SAML_SETTINGS_ID) });
  if (settings === undefined) throw new Error("SAML settings are unavailable");
  return settings;
}
export async function authLockoutResponse(
  set: SetObj,
  methods: Readonly<{ saml: boolean; oidc: boolean; ldap: boolean }>,
  localAuthEnabled?: boolean,
): Promise<{ errors: { status: string; title: string; detail: string }[] } | null> {
  const localAuth = localAuthEnabled ?? (await getSettings("general"))["local-auth-enabled"] !== false;
  if (localAuth || methods.saml || methods.oidc || methods.ldap) return null;
  (set as { status: number }).status = 422;
  return {
    errors: [{
      status: "422",
      title: "Unprocessable Entity",
      detail: "At least one authentication method must remain enabled",
    }],
  };
}
export function samlSettingsResource(
  settings: SamlSettings,
  request: Readonly<{ url: string }>,
  linkByEmail = false,
): Record<string, unknown> {
  return {
    id: SAML_SETTINGS_ID,
    type: "saml-settings",
    attributes: {
      enabled: settings.enabled,
      debug: settings.debug,
      "provider-type": "unknown",
      "old-idp-cert": settings.oldIdpCert,
      "idp-cert": settings.idpCert,
      "idp-entity-id": settings.idpEntityId,
      "slo-endpoint-url": settings.sloEndpointUrl,
      "sso-endpoint-url": settings.ssoEndpointUrl,
      "attr-username": settings.attrUsername,
      "attr-email": settings.attrEmail,
      "attr-groups": settings.attrGroups,
      "attr-site-admin": settings.attrSiteAdmin,
      "site-admin-role": settings.siteAdminRole,
      "sso-api-token-session-timeout": settings.ssoApiTokenSessionTimeout,
      "link-by-email": linkByEmail,
      "acs-consumer-url": apiURL(request, "/users/saml/auth"),
      "metadata-url": apiURL(request, "/users/saml/metadata"),
      "authn-requests-signed": false,
      "want-assertions-signed": false,
      "team-management-enabled": false,
      "signature-signing-method": "SHA256",
      "signature-digest-method": "SHA256",
    },
  };
}
export function validHttpsUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "https:" && url.username === "" && url.password === "";
  } catch {
    return false;
  }
}
export function validOidcIssuer(value: string): boolean {
  try {
    const url = new URL(value);
    const hostname = url.hostname.replace(/^\[|\]$/g, "").toLowerCase();
    const loopback = hostname === "localhost" || hostname === "127.0.0.1" || hostname === "::1";
    return (url.protocol === "https:" || (url.protocol === "http:" && loopback))
      && url.username === "" && url.password === "" && url.search === "" && url.hash === "";
  } catch {
    return false;
  }
}
export function normalizeIssuer(value: string): string {
  return value.trim();
}
export function samlInput(
  attributes: Readonly<Record<string, unknown>>,
  current: SamlSettings,
): Readonly<{ values: typeof samlSettings.$inferInsert }> | Readonly<{ error: string }> {
  for (const key of ["enabled", "debug"] as const) {
    if (attributes[key] !== undefined && typeof attributes[key] !== "boolean") {
      return { error: `${key} must be a boolean` };
    }
  }
  for (const key of [
    "idp-cert",
    "idp-entity-id",
    "slo-endpoint-url",
    "sso-endpoint-url",
    "attr-username",
    "attr-email",
    "attr-groups",
    "attr-site-admin",
    "site-admin-role",
  ] as const) {
    if (attributes[key] !== undefined && attributes[key] !== null && typeof attributes[key] !== "string") {
      return { error: `${key} must be a string or null` };
    }
  }
  const timeout = attributes["sso-api-token-session-timeout"];
  if (timeout !== undefined && !(typeof timeout === "number" && Number.isSafeInteger(timeout) && timeout >= 0)) {
    return { error: "sso-api-token-session-timeout must be a non-negative integer" };
  }
  const nullableString = (key: "idp-cert" | "idp-entity-id" | "slo-endpoint-url" | "sso-endpoint-url", fallback: string | null): string | null =>
    attributes[key] === undefined ? fallback : typeof attributes[key] === "string" ? attributes[key].trim() : null;
  // idp-cert must round-trip byte-for-byte (the provider compares it exactly,
  // including trailing newlines); trim would cause an inconsistent result.
  const rawCertString = (fallback: string | null): string | null =>
    attributes["idp-cert"] === undefined ? fallback : typeof attributes["idp-cert"] === "string" ? attributes["idp-cert"] : null;
  const requiredString = (
    key: "attr-username" | "attr-email" | "attr-groups" | "attr-site-admin" | "site-admin-role",
    fallback: string,
  ): string => attributes[key] === undefined ? fallback : typeof attributes[key] === "string" ? attributes[key].trim() : "";
  const idpCert = rawCertString(current.idpCert);
  const sloEndpointUrl = nullableString("slo-endpoint-url", current.sloEndpointUrl);
  const ssoEndpointUrl = nullableString("sso-endpoint-url", current.ssoEndpointUrl);
  // The tfe_saml_settings resource does not expose idp-entity-id; the reference format derives a
  // default entity ID when the SSO endpoint is known.
  const idpEntityId = nullableString("idp-entity-id", current.idpEntityId) ?? ssoEndpointUrl;
  const attrUsername = requiredString("attr-username", current.attrUsername);
  const attrEmail = requiredString("attr-email", current.attrEmail);
  const attrGroups = requiredString("attr-groups", current.attrGroups);
  const attrSiteAdmin = requiredString("attr-site-admin", current.attrSiteAdmin);
  const siteAdminRole = requiredString("site-admin-role", current.siteAdminRole);
  const enabled = typeof attributes.enabled === "boolean" ? attributes.enabled : current.enabled;
  if (idpCert !== null && idpCert !== "" && (
    !idpCert.includes("-----BEGIN CERTIFICATE-----")
    || !idpCert.includes("-----END CERTIFICATE-----")
  )) return { error: "idp-cert must be a PEM encoded X.509 certificate" };
  if (sloEndpointUrl !== null && sloEndpointUrl !== "" && !validHttpsUrl(sloEndpointUrl)) return { error: "slo-endpoint-url must be an HTTPS URL" };
  if (ssoEndpointUrl !== null && ssoEndpointUrl !== "" && !validHttpsUrl(ssoEndpointUrl)) return { error: "sso-endpoint-url must be an HTTPS URL" };
  if (attrUsername === "" || attrEmail === "" || attrGroups === "" || attrSiteAdmin === "" || siteAdminRole === "") {
    return { error: "attr-username, attr-email, attr-groups, attr-site-admin, and site-admin-role must not be empty" };
  }
  if (enabled && (idpCert === null || idpCert === "" || idpEntityId === null || idpEntityId === "" || ssoEndpointUrl === null || ssoEndpointUrl === "")) {
    return { error: "idp-cert, idp-entity-id, and sso-endpoint-url are required when SAML is enabled" };
  }
  return {
    values: {
      id: SAML_SETTINGS_ID,
      enabled,
      debug: typeof attributes.debug === "boolean" ? attributes.debug : current.debug,
      oldIdpCert: idpCert !== null && idpCert !== current.idpCert && current.idpCert !== null
        ? current.idpCert
        : current.oldIdpCert,
      idpCert,
      idpEntityId,
      sloEndpointUrl,
      ssoEndpointUrl,
      attrUsername,
      attrEmail,
      attrGroups,
      attrSiteAdmin,
      siteAdminRole,
      ssoApiTokenSessionTimeout: typeof timeout === "number" ? timeout : current.ssoApiTokenSessionTimeout,
      updatedAt: Date.now(),
    },
  };
}
export function gravatarUrl(email: string | null | undefined): string | null {
  const addr = (email ?? "").trim().toLowerCase();
  // Use a simple hash via built-in SHA-256 if available, otherwise fall back to a deterministic placeholder
  const hash = addr === "" ? "00000000000000000000000000000000" : Array.from(
    new Uint8Array(
      // Synchronous fallback: encode manually
      // We use a btoa-based digest approximation; for correctness we compute MD5-style hex of email
      // Since we cannot do crypto.subtle synchronously here, use a djb2 hex stretch
      ((): ArrayBuffer => {
        let h = 5381;
        for (let i = 0; i < addr.length; i++) h = ((h * 33) ^ addr.charCodeAt(i)) >>> 0;
        const buf = new Uint8Array(16);
        for (let i = 0; i < 16; i++) { buf[i] = (h >> (i % 4 * 8)) & 0xff; }
        return buf.buffer;
      })()
    )
  ).map((b: number): string => b.toString(16).padStart(2, "0")).join("");
  const raw = `https://www.gravatar.com/avatar/${hash}?s=80&d=identicon`;
  return AvatarService.resolveUrl("user-gravatar", raw);
}
export function adminUserResource(u: UserItem): Record<string, unknown> {
  return {
    id: u.id,
    type: "users",
    attributes: {
      username: u.username,
      email: u.email,
      "is-site-admin": u.isSiteAdmin === true,
      "is-admin": u.isSiteAdmin === true,
      "is-site-auditor": (u as Record<string, unknown>).isSiteAuditor === true,
      "is-suspended": (u as Record<string, unknown>).isSuspended === true,
      "avatar-url": gravatarUrl(u.email),
    },
  };
}
export function adminOrganizationResource(org: OrgItem): Record<string, unknown> {
  return {
    // go-tfe's AdminOrganization primary field is Name — jsonapi unmarshals the
    // response `id` into it, and the provider re-uses d.Id() for the
    // module-consumers calls. It MUST be the org NAME, not the UUID.
    id: org.name,
    type: "organizations",
    attributes: {
      name: org.name,
      "global-module-sharing": org.globalModuleSharing,
      "global-provider-sharing": org.globalProviderSharing,
      "access-beta-tools": org.accessBetaTools,
      "workspace-limit": org.workspaceLimit,
      "sso-enabled": org.samlEnabled,
      "saml-enabled": org.samlEnabled,
      "owners-team-saml-role-id": org.ownersTeamSamlRoleId,
      // The default IaC engine, so the admin org table reflects the org's
      // actual setting (Terraform vs OpenTofu) instead of a hardcoded fallback.
      "iac-binary": org.defaultIacBinary ?? "terraform",
    },
  };
}
export async function clearSpecificRegistrySharing(orgId: string, kind: "modules" | "providers"): Promise<void> {
  const rows = await db.query.registryPartnerships.findMany({ where: eq(registryPartnerships.producerOrgId, orgId) });
  for (const row of rows) {
    const otherEnabled = kind === "modules" ? row.providers : row.modules;
    if (otherEnabled) {
      await db.update(registryPartnerships)
        .set(kind === "modules" ? { modules: false } : { providers: false })
        .where(eq(registryPartnerships.id, row.id));
    } else {
      await db.delete(registryPartnerships).where(eq(registryPartnerships.id, row.id));
    }
  }
}
