import { AlertCircle, ChevronRight, RotateCcw, Sparkles } from "lucide-react";
import { formatExplainElapsed } from "@/lib/run-detail-format";
import type { PlanExplainer } from "@/lib/use-plan-explainer";
import { MarkdownContent } from "../MarkdownContent";
import { Button } from "../ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "../ui/dialog";
import { Spinner } from "../ui/spinner";

function ExplainerFooter({ explainer }: Readonly<{ explainer: PlanExplainer }>): React.JSX.Element | null {
  const { explaining, explanation, explainError } = explainer;
  if (!explaining && explanation === "" && explainError === "") return null;
  return (
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border px-5 py-3">
      <p className="min-w-0 truncate text-xs text-muted-foreground">
        {explainer.explainerModel !== "" ? `Generated by ${explainer.explainerModel}${explainer.explainerReasoningEffort !== null ? ` - ${explainer.explainerReasoningEffort}` : ""}` : ""}
      </p>
      <div className="flex items-center gap-2">
        {explaining ? (
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={explainer.cancelExplanation}
            aria-label="Cancel explanation generation"
          >
            Cancel
          </Button>
        ) : (
          explanation !== "" || explainError !== "" ? (
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={(): void => { void explainer.handleExplain(explainer.explainerKind, true); }}
              aria-label={explanation !== "" ? "Regenerate the explanation" : "Try generating the explanation again"}
              title={explanation !== "" ? "Regenerate" : "Try again"}
            >
              <RotateCcw data-icon="inline-start" className="size-4" aria-hidden="true" />
              {explanation !== "" ? "Regenerate" : "Try again"}
            </Button>
          ) : null
        )}
      </div>
    </div>
  );
}

export function ExplainerDialog({ explainer }: Readonly<{ explainer: PlanExplainer }>): React.JSX.Element {
  const { explaining, explanation, explainError, explainerThinking } = explainer;
  return (
    <Dialog
      open={explainer.explainerOpen}
      onOpenChange={(open): void => {
        if (!open) explainer.cancelExplanation();
        explainer.setExplainerOpen(open);
      }}
    >
      <DialogContent className="flex max-h-[80dvh] flex-col gap-0 overflow-hidden overscroll-contain p-0 sm:max-w-2xl">
        <DialogHeader className="border-b border-border px-5 py-4 pr-16 text-left">
          <DialogTitle className="flex items-center gap-2 text-base">
            <Sparkles className="size-4 text-primary" aria-hidden="true" />
            {explainer.explainerKind === "apply" ? "Apply failure explanation" : "Plan explanation"}
          </DialogTitle>
          <DialogDescription className="sr-only">
            A plain-language explanation generated from the stored {explainer.explainerKind === "apply" ? "apply failure" : "plan"} data.
          </DialogDescription>
        </DialogHeader>
        <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-5 py-4" aria-live="polite" aria-busy={explaining}>
          {explainError !== "" && (
            <div role="alert" className="flex items-start gap-2 rounded-md border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">
              <AlertCircle className="mt-0.5 size-4 shrink-0" aria-hidden="true" />
              <div>
                <p className="font-medium">Could not generate an explanation</p>
                <p className="mt-1 break-words">{explainError}</p>
                <p className="mt-2 text-xs text-destructive/90">Check the explainer endpoint, model, and API key, then try again.</p>
              </div>
            </div>
          )}
          {explaining && (
            <details
              className="group mb-3 rounded-md border border-border"
              open={explainer.explainerThinkingOpen}
              onToggle={(event): void => { explainer.setExplainerThinkingOpen(event.currentTarget.open); }}
            >
              <summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-3 py-2 text-xs font-medium text-muted-foreground hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring">
                <span className="flex min-w-0 items-center gap-2">
                  <ChevronRight className="size-3.5 text-muted-foreground transition-transform group-open:rotate-90" aria-hidden="true" />
                  <span>Thinking</span>
                </span>
                <span className="flex shrink-0 items-center gap-2 tabular-nums">
                  <Spinner className="size-3.5" aria-label="Thinking in progress" />
                  <span>{formatExplainElapsed(explainer.explainerElapsedSeconds)}</span>
                </span>
              </summary>
              <div className="border-t border-border px-3 py-2 text-xs leading-5 text-muted-foreground">
                <p className="break-words whitespace-pre-wrap">{explainerThinking !== "" ? explainerThinking : "Reasoning will appear here if the model provides it."}</p>
              </div>
            </details>
          )}
          {explaining && explanation === "" && explainerThinking === "" && (
            <div className="flex items-center gap-3 py-8 text-sm text-muted-foreground">
              <Spinner className="size-4" />
              Generating explanation…
            </div>
          )}
          {explanation !== "" && (
            <MarkdownContent markdown={explanation} className="break-words text-sm leading-6 text-foreground" />
          )}
        </div>
        <ExplainerFooter explainer={explainer} />
      </DialogContent>
    </Dialog>
  );
}
